apiVersion: core.gardener.cloud/v1beta1
kind: CloudProfile
metadata:
  name: local
spec:
  type: local
  regions:
  - name: local
  kubernetes:
    versions:
    - version: 1.22.0
    - version: 1.21.0
    - version: 1.20.0
    - version: 1.19.0
    - version: 1.18.0
  machineImages:
  - name: local
    versions:
    - cri:
      - name: containerd
      version: 0.0.1
  machineTypes:
  - cpu: "1"
    gpu: "0"
    memory: 1Gi
    name: local
